services:
    creonit_admin.storage_module:
        class: Degit22\StorageBundle\Admin\StorageModule
        tags: [{ name: creonit_admin.module }]

    degit22_storage:
        class: Degit22\StorageBundle\Service\StorageService
        arguments: ['@service_container']
